version: "3.9"

volumes:
  local-postgres-data:

services:
  osta_crawler:
    image: havardox/osta_crawler:latest
    container_name: osta_crawler
    restart: "no"
    build:
      context: .
      dockerfile: ./compose/osta_crawler/Dockerfile
      target: base
      tags:
        - havardox/osta_crawler:0.2.0
    
    volumes:
      - .:/home/node/app/src
      - /home/node/app
    env_file:
      - .envs/osta_crawler/dev.env

    depends_on:
      osta_crawler_db:
        condition: service_healthy
      
  osta_crawler_db:
    image: postgres:13.5-alpine
    container_name: osta_crawler_db 
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    ports:
    - "2475:2475"
    volumes:
      # - ./compose/postgres/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/osta_crawler_db/dev.env
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s